2018-03-22 15:41:47,519 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:46]
2018-03-22 15:43:57,577 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:46]
2018-03-22 15:44:13,145 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:46]
2018-03-22 15:44:19,891 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:46]
2018-03-22 15:46:04,015 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:46]
2018-03-22 15:48:03,060 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:46]
2018-03-22 15:48:47,903 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:46]
2018-03-22 15:48:55,813 ERROR: Exception on /edit_profile [GET] [in c:\gardenapp\blogvenv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\GardenApp\app\routes.py", line 80, in edit_profile
    form = EditProfileForm()
  File "c:\gardenapp\blogvenv\lib\site-packages\wtforms\form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'original_username'
2018-03-22 15:50:18,596 ERROR: Exception on /edit_profile [GET] [in c:\gardenapp\blogvenv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\GardenApp\app\routes.py", line 80, in edit_profile
    form = EditProfileForm()
  File "c:\gardenapp\blogvenv\lib\site-packages\wtforms\form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'original_username'
2018-03-22 15:50:34,980 ERROR: Exception on /edit_profile [GET] [in c:\gardenapp\blogvenv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\GardenApp\app\routes.py", line 80, in edit_profile
    form = EditProfileForm()
  File "c:\gardenapp\blogvenv\lib\site-packages\wtforms\form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'original_username'
2018-03-22 15:55:19,715 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:46]
2018-03-22 15:55:38,946 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:46]
2018-03-22 15:58:09,954 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:46]
2018-03-22 15:58:13,029 ERROR: Exception on /edit_profile [GET] [in c:\gardenapp\blogvenv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\GardenApp\app\routes.py", line 80, in edit_profile
    form = EditProfileForm()
  File "c:\gardenapp\blogvenv\lib\site-packages\wtforms\form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'original_username'
2018-03-22 15:59:34,051 ERROR: Exception on /edit_profile [GET] [in c:\gardenapp\blogvenv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\GardenApp\app\routes.py", line 80, in edit_profile
    form = EditProfileForm(current_user.username)
  File "c:\gardenapp\blogvenv\lib\site-packages\wtforms\form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'original_username'
2018-03-22 15:59:54,818 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:46]
2018-03-22 16:01:22,326 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:46]
2018-03-22 23:49:40,396 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:46]
