2018-06-25 16:31:45,718 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-07-04 15:20:44,238 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-07-04 15:24:21,071 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-07-04 15:26:10,055 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-07-04 15:48:29,994 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-07-04 15:51:16,207 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-07-04 15:51:24,595 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-07-04 15:53:12,456 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-07-04 15:53:15,009 ERROR: Exception on /api/gardens/map [GET] [in c:\gardenapp\blogvenv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_httpauth.py", line 93, in decorated
    return f(*args, **kwargs)
  File "C:\GardenApp\app\api\gardens.py", line 16, in get_all_gardens_for_maps
    return jsonify(data)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\json.py", line 263, in jsonify
    (dumps(data, indent=indent, separators=separators), '\n'),
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\json.py", line 123, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\Python36\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Python36\lib\json\encoder.py", line 201, in encode
    chunks = list(chunks)
  File "C:\Python36\lib\json\encoder.py", line 430, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Python36\lib\json\encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "C:\Python36\lib\json\encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "C:\Python36\lib\json\encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "C:\Python36\lib\json\encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "C:\Python36\lib\json\encoder.py", line 437, in _iterencode
    o = _default(o)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\json.py", line 80, in default
    return _json.JSONEncoder.default(self, o)
  File "C:\Python36\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Plant' is not JSON serializable
2018-07-05 17:11:59,609 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-07-05 17:12:49,674 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-07-05 17:12:59,183 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-07-05 17:13:50,114 ERROR: Exception on /api/gardens/map [GET] [in c:\gardenapp\blogvenv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_httpauth.py", line 93, in decorated
    return f(*args, **kwargs)
  File "C:\GardenApp\app\api\gardens.py", line 15, in get_all_gardens_for_maps
    data = Garden.to_collection_dict(Garden.query, page, per_page, 'api.get_all_gardens_for_maps')
  File "C:\GardenApp\app\models.py", line 19, in to_collection_dict
    'items': [item.to_dict() for item in resources.items],
  File "C:\GardenApp\app\models.py", line 19, in <listcomp>
    'items': [item.to_dict() for item in resources.items],
  File "C:\GardenApp\app\models.py", line 224, in to_dict
    'plants': self.get_plants_to_dict()
TypeError: get_plants_to_dict() takes 0 positional arguments but 1 was given
2018-07-05 17:21:08,245 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-07-05 17:23:51,378 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-07-05 17:23:55,938 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-07-05 18:36:42,762 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-07-05 18:37:12,822 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-07-05 18:37:22,427 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-07-05 18:37:27,637 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-07-09 21:02:07,855 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-07-09 21:05:00,377 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-07-09 21:10:17,602 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-07-09 21:19:47,559 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-07-09 21:28:41,757 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-07-09 21:29:01,745 ERROR: Exception on /api/gardens/map [GET] [in c:\gardenapp\blogvenv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_httpauth.py", line 93, in decorated
    return f(*args, **kwargs)
  File "C:\GardenApp\app\api\gardens.py", line 15, in get_all_gardens_for_maps
    data = Garden.to_collection_dict(Garden.query.filter(Garden.lat != None and Garden.lon != None), page, per_page, 'api.get_all_gardens_for_maps')
  File "c:\gardenapp\blogvenv\lib\site-packages\sqlalchemy\sql\elements.py", line 2975, in __bool__
    raise TypeError("Boolean value of this clause is not defined")
TypeError: Boolean value of this clause is not defined
2018-07-09 21:31:28,077 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-07-09 21:33:08,693 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-07-09 21:34:04,176 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-07-09 22:23:38,520 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-07-13 15:52:09,847 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
