2018-05-14 17:33:07,999 ERROR: Exception on /reset_password_request [POST] [in c:\gardenapp\blogvenv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\GardenApp\app\routes.py", line 119, in reset_password_request
    send_password_reset_email(user)
  File "C:\GardenApp\app\email.py", line 28, in send_password_reset_email
    user=user, token=token))
  File "C:\GardenApp\app\email.py", line 17, in send_email
    mail.send(msg)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_mail.py", line 165, in configure_host
    host.login(self.mail.username, self.mail.password)
  File "C:\Python36\lib\smtplib.py", line 696, in login
    "SMTP AUTH extension not supported by server.")
smtplib.SMTPNotSupportedError: SMTP AUTH extension not supported by server.
2018-05-14 17:34:16,042 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:52]
2018-05-14 17:34:27,372 ERROR: Exception on /reset_password_request [POST] [in c:\gardenapp\blogvenv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\GardenApp\app\routes.py", line 119, in reset_password_request
    send_password_reset_email(user)
  File "C:\GardenApp\app\email.py", line 28, in send_password_reset_email
    user=user, token=token))
  File "C:\GardenApp\app\email.py", line 17, in send_email
    mail.send(msg)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_mail.py", line 165, in configure_host
    host.login(self.mail.username, self.mail.password)
  File "C:\Python36\lib\smtplib.py", line 696, in login
    "SMTP AUTH extension not supported by server.")
smtplib.SMTPNotSupportedError: SMTP AUTH extension not supported by server.
2018-05-14 17:44:21,596 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:52]
2018-05-14 17:49:31,702 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:52]
2018-05-14 17:49:37,418 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:52]
2018-05-14 17:49:44,613 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:52]
2018-05-14 17:50:08,605 ERROR: Exception on /reset_password_request [POST] [in c:\gardenapp\blogvenv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\GardenApp\app\routes.py", line 120, in reset_password_request
    send_password_reset_email(user)
  File "C:\GardenApp\app\email.py", line 28, in send_password_reset_email
    user=user, token=token))
  File "C:\GardenApp\app\email.py", line 17, in send_email
    mail.send(msg)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_mail.py", line 165, in configure_host
    host.login(self.mail.username, self.mail.password)
  File "C:\Python36\lib\smtplib.py", line 696, in login
    "SMTP AUTH extension not supported by server.")
smtplib.SMTPNotSupportedError: SMTP AUTH extension not supported by server.
2018-05-14 20:00:18,280 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:52]
2018-05-16 13:43:57,820 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:70]
2018-05-16 13:44:09,336 ERROR: Exception on /auth/login [GET] [in c:\gardenapp\blogvenv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\GardenApp\app\auth\routes.py", line 27, in login
    return render_template('auth/login.html', title='Sign In', form=form)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\templating.py", line 134, in render_template
    context, ctx.app)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\templating.py", line 116, in _render
    rv = template.render(context)
  File "c:\gardenapp\blogvenv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\gardenapp\blogvenv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\gardenapp\blogvenv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\gardenapp\blogvenv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\GardenApp\app\templates\auth\login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\GardenApp\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 21, in block "body"
    {% block navbar %}
  File "C:\GardenApp\app\templates\base.html", line 17, in block "navbar"
    <a class="navbar-brand" href="{{ url_for('index') }}">GardenApp</a>
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\helpers.py", line 323, in url_for
    force_external=external)
  File "c:\gardenapp\blogvenv\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'index'. Did you mean 'main.index' instead?
2018-05-16 13:46:02,241 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:70]
