2019-05-01 15:26:38,702 ERROR: Exception on /registerGardenFromMap/1116 NE Schuyler St, Portland, OR 97212, USA [GET] [in c:\gardenapp\blogvenv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\GardenApp\app\main\routes.py", line 289, in registerGardenFromMap
    form = GardenForm2()
NameError: name 'GardenForm2' is not defined
2019-05-01 15:26:51,228 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-01 15:32:16,321 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-01 15:33:08,487 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-01 18:43:59,523 ERROR: Exception on /registerGarden [GET] [in c:\gardenapp\blogvenv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\GardenApp\app\main\routes.py", line 267, in registerGarden
    wall_posts_page, current_app.config['POSTS_PER_PAGE'], False)
NameError: name 'alert' is not defined
2019-05-01 21:09:36,932 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-01 21:09:44,987 ERROR: Exception on /registerGarden [GET] [in c:\gardenapp\blogvenv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\GardenApp\app\main\routes.py", line 221, in registerGarden
    return render_template('registerGarden.html', title='Register Garden', form=form, address=address)
NameError: name 'address' is not defined
2019-05-01 21:09:48,103 ERROR: Exception on /registerGarden [GET] [in c:\gardenapp\blogvenv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\GardenApp\app\main\routes.py", line 221, in registerGarden
    return render_template('registerGarden.html', title='Register Garden', form=form, address=address)
NameError: name 'address' is not defined
2019-05-01 21:11:06,716 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-01 21:12:23,365 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-01 21:48:54,451 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-01 22:43:24,256 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-01 22:57:40,307 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-01 23:13:47,612 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-02 00:31:24,421 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-02 00:31:29,034 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-02 00:41:10,744 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-02 00:42:05,608 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-02 00:43:26,552 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-02 01:22:20,440 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-02 01:23:19,031 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-02 01:27:36,802 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-02 01:35:19,536 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-02 02:17:05,776 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-02 02:23:42,007 ERROR: Exception on /explore [GET] [in c:\gardenapp\blogvenv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\GardenApp\app\main\routes.py", line 149, in explore
    infobox2 = '<h3 style="strong">Plants at this location</h3><ul>{}</ul>{}'.format(container)
IndexError: tuple index out of range
2019-05-02 02:44:26,785 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-02 02:53:05,606 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-02 02:56:11,168 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-02 15:52:34,939 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-02 15:53:32,252 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-02 15:57:32,362 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-02 15:59:05,392 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-02 16:01:52,745 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-02 16:02:38,940 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-02 16:07:03,630 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-02 16:07:56,800 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-02 16:18:22,424 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-02 16:18:43,740 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-03 00:09:10,526 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-03 00:12:53,878 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-03 00:13:20,601 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
