2018-06-13 22:01:38,723 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-06-13 22:11:04,008 ERROR: Exception on /api/users [POST] [in c:\gardenapp\blogvenv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\GardenApp\app\api\users.py", line 40, in create_user
    return bad_request('must include username, email and password fields')
TypeError: bad_request() takes 0 positional arguments but 1 was given
2018-06-13 22:11:59,141 ERROR: Exception on /api/users [POST] [in c:\gardenapp\blogvenv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\GardenApp\app\api\users.py", line 42, in create_user
    return bad_request('please use a different username')
TypeError: bad_request() takes 0 positional arguments but 1 was given
2018-06-13 22:13:04,621 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-06-13 22:16:16,526 ERROR: Exception on /api/users [POST] [in c:\gardenapp\blogvenv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\GardenApp\app\api\users.py", line 51, in create_user
    response.headers['Location'] = url_for('api.get_user', id=user.id)
NameError: name 'url_for' is not defined
2018-06-13 22:16:49,143 ERROR: Exception on /api/users [POST] [in c:\gardenapp\blogvenv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\GardenApp\app\api\users.py", line 42, in create_user
    return bad_request('please use a different username')
TypeError: bad_request() takes 0 positional arguments but 1 was given
2018-06-13 22:18:03,884 ERROR: Exception on /api/users [POST] [in c:\gardenapp\blogvenv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\GardenApp\app\api\users.py", line 51, in create_user
    response.headers['Location'] = url_for('api.get_user', id=user.id)
NameError: name 'url_for' is not defined
2018-06-13 22:18:59,261 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-06-14 13:55:10,381 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-06-14 13:55:14,106 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-06-14 14:13:33,636 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-06-14 14:15:09,766 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-06-14 14:16:48,293 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-06-14 14:18:46,526 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-06-14 14:19:22,340 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-06-14 14:19:45,166 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-06-14 15:04:49,618 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-06-14 15:09:04,688 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-06-14 15:10:13,215 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-06-14 15:15:33,613 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-06-14 15:16:18,847 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-06-14 15:19:59,625 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-06-14 15:21:00,863 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-06-14 15:21:15,092 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-06-14 15:23:08,641 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-06-14 15:24:34,781 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-06-14 15:25:14,755 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-06-14 15:26:51,032 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-06-14 15:27:55,987 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-06-14 15:29:56,463 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-06-14 15:30:43,742 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-06-14 15:32:31,837 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-06-14 15:33:35,548 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-06-14 15:34:27,118 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-06-14 15:39:37,615 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-06-15 15:24:07,511 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-06-15 15:36:53,862 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-06-15 15:38:04,925 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-06-15 15:58:40,934 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-06-15 17:20:54,186 ERROR: Exception on /api/users [POST] [in c:\gardenapp\blogvenv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\GardenApp\app\api\users.py", line 42, in create_user
    @token_auth.login_required
TypeError: bad_request() takes 0 positional arguments but 1 was given
2018-06-19 15:46:06,853 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-06-19 20:25:37,348 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-06-19 20:26:18,807 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2018-06-19 20:36:31,124 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
