2019-05-01 14:33:21,175 ERROR: Exception on /placementMap [GET] [in c:\gardenapp\blogvenv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\GardenApp\app\main\routes.py", line 53, in placementMap
    return render_template("placementMap.html", placementmap=placementmap, lat=lat, lng=lng)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\templating.py", line 134, in render_template
    context, ctx.app)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\templating.py", line 116, in _render
    rv = template.render(context)
  File "c:\gardenapp\blogvenv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\gardenapp\blogvenv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\gardenapp\blogvenv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\gardenapp\blogvenv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\GardenApp\app\templates\placementMap.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\GardenApp\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\GardenApp\app\templates\base.html", line 52, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\GardenApp\app\templates\placementMap.html", line 7, in block "app_content"
    <head>{{placementmap.js}}</head>
  File "c:\gardenapp\blogvenv\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_googlemaps\__init__.py", line 749, in js
    DEFAULT_ICON=DEFAULT_ICON
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_googlemaps\__init__.py", line 709, in render
    return render_template(*args, **kwargs)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\templating.py", line 134, in render_template
    context, ctx.app)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\templating.py", line 116, in _render
    rv = template.render(context)
  File "c:\gardenapp\blogvenv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\gardenapp\blogvenv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\gardenapp\blogvenv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\gardenapp\blogvenv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_googlemaps\templates\googlemaps\gmapjs.html", line 228, in top-level template code
    html = '<p><a href="{{ url_for(url, address=xxxx) }}">xxxx</a></p><br>'.replace('xxxx', address);
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\helpers.py", line 280, in url_for
    if endpoint[:1] == '.':
jinja2.exceptions.UndefinedError: 'url' is undefined
2019-05-01 14:34:16,736 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-01 14:36:23,726 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-01 14:36:26,723 ERROR: Exception on /placementMap [GET] [in c:\gardenapp\blogvenv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\GardenApp\app\main\routes.py", line 53, in placementMap
    return render_template("placementMap.html", placementmap=placementmap, lat=lat, lng=lng)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\templating.py", line 134, in render_template
    context, ctx.app)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\templating.py", line 116, in _render
    rv = template.render(context)
  File "c:\gardenapp\blogvenv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\gardenapp\blogvenv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\gardenapp\blogvenv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\gardenapp\blogvenv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\GardenApp\app\templates\placementMap.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\GardenApp\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\GardenApp\app\templates\base.html", line 52, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\GardenApp\app\templates\placementMap.html", line 7, in block "app_content"
    <head>{{placementmap.js}}</head>
  File "c:\gardenapp\blogvenv\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_googlemaps\__init__.py", line 749, in js
    DEFAULT_ICON=DEFAULT_ICON
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_googlemaps\__init__.py", line 709, in render
    return render_template(*args, **kwargs)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\templating.py", line 134, in render_template
    context, ctx.app)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\templating.py", line 116, in _render
    rv = template.render(context)
  File "c:\gardenapp\blogvenv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\gardenapp\blogvenv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\gardenapp\blogvenv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\gardenapp\blogvenv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_googlemaps\templates\googlemaps\gmapjs.html", line 228, in top-level template code
    html = '<p><a href="{{ url_for(uri, address=xxxx) }}">xxxx</a></p><br>'.replace('xxxx', address).replace('uri', uri);
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\helpers.py", line 280, in url_for
    if endpoint[:1] == '.':
jinja2.exceptions.UndefinedError: 'uri' is undefined
2019-05-01 14:37:59,240 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
