2019-05-05 18:05:29,861 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-05 18:06:24,000 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-05 18:06:53,354 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-05 21:06:32,548 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-05 21:10:16,132 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-05 21:11:00,229 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-05 21:21:08,607 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-05 21:45:58,161 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-06 10:10:43,407 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-06 10:27:58,006 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-06 10:28:16,305 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-06 10:28:42,943 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-06 10:29:04,207 ERROR: Exception on /index [GET] [in c:\gardenapp\blogvenv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\GardenApp\app\main\routes.py", line 72, in index
    markers= markers,
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_googlemaps\__init__.py", line 72, in __init__
    self.collapsible = collapsible
NameError: name 'collapsible' is not defined
2019-05-06 10:29:55,781 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-06 11:42:48,591 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-06 12:33:30,950 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-06 12:33:34,102 ERROR: Exception on /index [GET] [in c:\gardenapp\blogvenv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\GardenApp\app\main\routes.py", line 76, in index
    plants_next_url=plants_next_url, plants_prev_url=plants_prev_url, mymap=mymap, gardens=gardens)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\templating.py", line 134, in render_template
    context, ctx.app)
  File "c:\gardenapp\blogvenv\lib\site-packages\flask\templating.py", line 116, in _render
    rv = template.render(context)
  File "c:\gardenapp\blogvenv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\gardenapp\blogvenv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\gardenapp\blogvenv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\gardenapp\blogvenv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\GardenApp\app\templates\base.html", line 25, in template
    {% endblock %}
  File "c:\gardenapp\blogvenv\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "C:\GardenApp\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "c:\gardenapp\blogvenv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\gardenapp\blogvenv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\GardenApp\app\templates\base.html", line 25, in template
    {% endblock %}
  File "c:\gardenapp\blogvenv\lib\site-packages\jinja2\environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "c:\gardenapp\blogvenv\lib\site-packages\jinja2\parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "c:\gardenapp\blogvenv\lib\site-packages\jinja2\parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "c:\gardenapp\blogvenv\lib\site-packages\jinja2\parser.py", line 144, in parse_statement
    self.fail_unknown_tag(token.value, token.lineno)
  File "c:\gardenapp\blogvenv\lib\site-packages\jinja2\parser.py", line 97, in fail_unknown_tag
    return self._fail_ut_eof(name, self._end_token_stack, lineno)
  File "c:\gardenapp\blogvenv\lib\site-packages\jinja2\parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "c:\gardenapp\blogvenv\lib\site-packages\jinja2\parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'.
2019-05-06 12:35:34,540 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
2019-05-06 13:21:09,693 INFO: Microblog startup [in C:\GardenApp\app\__init__.py:76]
